name = "yagel-barber"
compatibility_date = "2026-09-30"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "yagel-barber"
database_id = "20edb0a6-5b9f-4af1-9780-874f0995af18"
migrations_dir = "migrations"
